version: "3.9"

services:
  devnet:
    image: shardlabs/starknet-devnet:latest
    container_name: devnet.container
    networks:
      - dev-network
    # volumes:
    #   - type: bind
    #     source: ./e2e/mocks/dumpdir
    #     target: /dumpdir
    # command: --load-path /dumpdir/dump.pkl

  nftmeta:
    image: clue/json-server
    container_name: nftmeta.container
    networks:
      - dev-network
    volumes:
      - type: bind
        source: ./nft-metadata-db.json
        target: /data/db.json
    command: --no-cors

  dapp:
    build:
      context: .
      dockerfile: dapp-container/Dockerfile
    container_name: dapp.container
    networks:
      - dev-network
    depends_on:
      - nftmeta

  # puppeteer:
  #   build:
  #     context: .
  #     dockerfile: puppeteer-container/Dockerfile
  #   container_name: puppeteer.container
  #   networks:
  #     - dev-network
  #   depends_on:
  #     - devnet
  #     - dapp
  #     - nftmeta
  #   environment:
  #     - CI=true
  #     - DAPP_HOST=dapp.container
  #   command:
  #     - yarn web:test
networks:
  dev-network:
    driver: bridge