name: Extension e2e tests
on:
  push:
    branches: [ "test-ci-branch2" ]
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      # - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      # - name: Verify git HEAD
      #   run: |
      #     [ "$(git rev-parse HEAD)" = "${{ github.sha }}" ]  
      # - name: Print branchname
      #   run: node branchname.js
      - name: Prepare environment
        run: npm i -g yarn && yarn install --frozen-lockfile
      - name: Build Extension application
        run: yarn web:build
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Build containers
        run: docker-compose build
      - name: Run containers 
        run: docker compose up --abort-on-container-exit
      - name: Watch tests 
        run: docker attach pupperteer
      # - name: Build Extension application
      #   run: yarn web:build
      # - name: Start devnet service container
      #   run: docker-compose run devnet
      # - name: Start nftmeta service container
      #   run: docker-compose run nftmeta
      # - name: Start dapp service container
      #   run: docker-compose run dapp
      # - name: Start tests
      #   run: 
