name: Extension e2e tests
on:
  pull_request_target:
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Prepare environment
        run: npm i -g yarn && yarn install --frozen-lockfile
      - name: Build Extension application
        run: yarn web:build
      - name: Test Extension
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: 'true'
        with:
          args: yarn web:test
