name: Extension e2e tests
# on:
#   pull_request_target:
on: push
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Create docker network
      #   run: docker network create --driver bridge test-network 
      - name: Check network created
        run: docker network ls
      - name: Launch docker container 
        run: |
          docker run -d \
          -p 127.0.0.1:5050:5050 \
          --restart always \
          --name devnet_container \
          --network test-network \
          shardlabs/starknet-devnet:latest

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Make a request from root
        run: node request.js

      # - name: Prepare environment
      #   run: npm i -g yarn && yarn install --frozen-lockfile

      # - name: Build Extension application
      #   run: yarn web:build

      # - name: Build container
      #   run: docker build -t test-image .


      - name: Puppeteer container
        run: |
          docker run -d \
          --restart always \
          --name puppeteer_container \
          --mount type=bind,source=${{ github.workspace }},target=/app \
          --network test-network \
          ghcr.io/puppeteer/puppeteer:latest \
          cd /app && npm i -g yarn && yarn install --frozen-lockfile && yarn web:build && yarn web:test

      - name: Stop container
        run: docker stop devnet_container

      - name: Delete container
        run: docker rm devnet_container
