name: Extension e2e tests
# on:
#   pull_request_target:
on: push
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Determine current location
        run: echo `pwd`/dumpdir
      - name: Launch docker container 
        run: |
          docker run -d \
          -p 127.0.0.1:5050:5050 \
          --restart always \
          --name devnet_container \
          --mount type=bind,source=${{ github.workspace }}/dumpdir,target=/dumpdir \
          shardlabs/starknet-devnet:latest \
          --dump-on exit \
          --dump-path /dumpdir/dump.pkl \
          --load-path /dumpdir/dump.pkl
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Make a request from root
        run: node request.js
      # - name: Make a request from puppeteer
      #   uses: mujo-code/puppeteer-headful@v2
      #   env:
      #     CI: 'true'
      #   with:
      #     # args: yarn web:test
      #     args: node request.js
      - name: Run Puppeteer container
        run: |
          docker build -t test-pup . && \
          docker run --network="host" test-pup yarn web:test
      - name: Sleep for 5 seconds
        run: sleep 5s
      - name: Stop container
        run: docker stop devnet_container
      - name: Delete container
        run: docker rm devnet_container
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
