name: GitHub Actions Demo
on:
  pull_request:
    branches: 
      - github-actions
    types: [closed]
jobs:
  GitHub-Actions-Merge-Master:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: '16.x'
      - name: Prepare environment
        run: npm i -g yarn && yarn install --frozen-lockfile
      - name: Build Extension application
        run: yarn build
      - name: Test Extension
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: 'true'
        with:
          args: yarn e2e
